import type { Epic, Story } from '@landi-flow/core/types';
import { EPIC_STATUS_IDS } from '@/lib/epic-status';
import { WORKFLOW_STATES } from '@/lib/workflow-states';

export { WORKFLOW_STATES, workflowStateToStatus } from '@/lib/workflow-states';

export const DEMO_WORKSPACE_ID = 'ws-landi-flow-demo';
export const DEMO_TEAM_ID = 'team-design';

export const SEED_EPICS: Epic[] = [
  {
    id: 'epic-001',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Progressive Disclosure Shell',
    slug: 'progressive-disclosure-shell',
    description_json: null,
    description_md:
      'Build the adaptive UI shell that balances power-user keyboard flows with novice discoverability.',
    status_id: EPIC_STATUS_IDS.in_progress,
    priority: 'high',
    lead_id: 'user-jane',
    start_date: '2026-07-01',
    target_date: '2026-08-01',
    progress_cache: { story_count: 3, done_count: 1 },
    correlation_id: null,
    archived_at: null,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-04T12:00:00.000Z',
  },
  {
    id: 'epic-002',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Agent Collaboration Plane',
    slug: 'agent-collaboration-plane',
    description_json: null,
    description_md:
      'First-class AI agents as workspace members with governed write paths and activity streams.',
    status_id: EPIC_STATUS_IDS.planned,
    priority: 'medium',
    lead_id: null,
    start_date: null,
    target_date: null,
    progress_cache: null,
    correlation_id: null,
    archived_at: null,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-02T14:00:00.000Z',
  },
  {
    id: 'epic-003',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'OBS-001 Observability Spine',
    slug: 'obs-001-observability-spine',
    description_json: null,
    description_md:
      'End-to-end correlation IDs from client error boundaries through Workers to AI Gateway.',
    status_id: EPIC_STATUS_IDS.backlog,
    priority: 'urgent',
    lead_id: null,
    start_date: null,
    target_date: null,
    progress_cache: null,
    correlation_id: null,
    archived_at: null,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-01T10:00:00.000Z',
  },
  {
    id: 'epic-004',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Epic Board Polish',
    slug: 'epic-board-polish',
    description_json: null,
    description_md: 'Kanban-style Epic roadmap with burn-up progress and dependency hints.',
    status_id: EPIC_STATUS_IDS.completed,
    priority: 'none',
    lead_id: 'user-alex',
    start_date: '2026-06-15',
    target_date: '2026-06-28',
    progress_cache: { story_count: 1, done_count: 1 },
    correlation_id: null,
    archived_at: null,
    created_at: '2026-06-15T10:00:00.000Z',
    updated_at: '2026-06-28T16:00:00.000Z',
  },
];

export const SEED_STORIES: Story[] = [
  {
    id: 'story-001',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 1,
    epic_id: 'epic-001',
    identifier: 'LAN-1',
    title: 'Implement three-panel SidebarLayout shell',
    description_json: null,
    description_md:
      'Wire SidebarLayout from @landi-flow/ui with collapsible sidebar and inspector.',
    priority: 'high',
    workflow_state_id: WORKFLOW_STATES.done,
    assignee_id: 'user-jane',
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: 3,
    due_date: null,
    sort_order: 1,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-02T09:00:00.000Z',
    updated_at: '2026-07-04T11:00:00.000Z',
  },
  {
    id: 'story-002',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 2,
    epic_id: 'epic-001',
    identifier: 'LAN-2',
    title: 'Command palette with suggested actions',
    description_json: null,
    description_md: 'Cmd+K palette shows contextual suggested actions when query is empty.',
    priority: 'medium',
    workflow_state_id: WORKFLOW_STATES.in_progress,
    assignee_id: 'user-jane',
    delegate_agent_id: 'agent-cursor',
    milestone_id: null,
    cycle_id: null,
    estimate: 2,
    due_date: null,
    sort_order: 2,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-02T10:00:00.000Z',
    updated_at: '2026-07-04T12:30:00.000Z',
  },
  {
    id: 'story-003',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 3,
    epic_id: 'epic-001',
    identifier: 'LAN-3',
    title: 'G-key navigation tooltips',
    description_json: null,
    description_md:
      'Press G and pause 500ms to reveal secondary keystroke hints on nav targets.',
    priority: 'low',
    workflow_state_id: WORKFLOW_STATES.todo,
    assignee_id: null,
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: 1,
    due_date: null,
    sort_order: 3,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-03T08:00:00.000Z',
    updated_at: '2026-07-03T08:00:00.000Z',
  },
  {
    id: 'story-004',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 4,
    epic_id: 'epic-002',
    identifier: 'LAN-4',
    title: 'Agent avatar active-state glow',
    description_json: null,
    description_md: 'Animated border on agent avatars when background processing is active.',
    priority: 'medium',
    workflow_state_id: WORKFLOW_STATES.todo,
    assignee_id: null,
    delegate_agent_id: 'agent-cursor',
    milestone_id: null,
    cycle_id: null,
    estimate: 2,
    due_date: null,
    sort_order: 4,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-03T11:00:00.000Z',
    updated_at: '2026-07-03T11:00:00.000Z',
  },
  {
    id: 'story-005',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 5,
    epic_id: 'epic-003',
    identifier: 'LAN-5',
    title: 'Error boundary with correlation ID',
    description_json: null,
    description_md: 'Inline ErrorFallback cards include copyable trace IDs per OBS-001.',
    priority: 'urgent',
    workflow_state_id: WORKFLOW_STATES.in_progress,
    assignee_id: 'user-alex',
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: 2,
    due_date: null,
    sort_order: 5,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-04T08:00:00.000Z',
    updated_at: '2026-07-04T13:00:00.000Z',
  },
  {
    id: 'story-006',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 6,
    epic_id: 'epic-004',
    identifier: 'LAN-6',
    title: 'Epic board column layout',
    description_json: null,
    description_md: 'Status columns with Epic cards, progress chips, and empty-state CTA.',
    priority: 'none',
    workflow_state_id: WORKFLOW_STATES.done,
    assignee_id: 'user-alex',
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: 3,
    due_date: null,
    sort_order: 6,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-06-20T09:00:00.000Z',
    updated_at: '2026-06-28T15:00:00.000Z',
  },
];

export function getEpicById(epicId: string): Epic | undefined {
  return SEED_EPICS.find((epic) => epic.id === epicId);
}

export function getStoriesForEpic(epicId: string): Story[] {
  return SEED_STORIES.filter((story) => story.epic_id === epicId);
}

export function getStoryById(storyId: string): Story | undefined {
  return SEED_STORIES.find((story) => story.id === storyId);
}
