import type { CustomerRequest, Cycle, Epic, Milestone, Story, View, WorkflowState } from '@landi-flow/core/types';
import { EPIC_STATUS_IDS } from '@/lib/epic-status';
import { WORKFLOW_STATES } from '@/lib/workflow-states';

export { WORKFLOW_STATES, workflowStateToStatus } from '@/lib/workflow-states';

export const DEMO_WORKSPACE_ID = 'ws-landi-flow-demo';
export const DEMO_TEAM_ID = 'team-design';

/** Demo Kanban columns for collaborative board in local/dev. */
export const DEMO_WORKFLOW_STATE_ROWS: WorkflowState[] = [
  { id: WORKFLOW_STATES.triage, team_id: DEMO_TEAM_ID, name: 'Triage', category: 'triage', position: -1, is_default: false },
  { id: WORKFLOW_STATES.todo, team_id: DEMO_TEAM_ID, name: 'Todo', category: 'unstarted', position: 0, is_default: true },
  { id: WORKFLOW_STATES.in_progress, team_id: DEMO_TEAM_ID, name: 'In Progress', category: 'started', position: 1, is_default: false },
  { id: WORKFLOW_STATES.done, team_id: DEMO_TEAM_ID, name: 'Done', category: 'completed', position: 2, is_default: false },
  { id: WORKFLOW_STATES.canceled, team_id: DEMO_TEAM_ID, name: 'Canceled', category: 'canceled', position: 3, is_default: false },
];

export const SEED_EPICS: Epic[] = [
  {
    id: 'epic-001',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Progressive Disclosure Shell',
    slug: 'progressive-disclosure-shell',
    description_json: null,
    description_md:
      'Build the adaptive UI shell that balances power-user keyboard flows with novice discoverability.',
    status_id: EPIC_STATUS_IDS.in_progress,
    priority: 'high',
    lead_id: 'user-jane',
    delegate_agent_id: null,
    start_date: '2026-07-01',
    target_date: '2026-08-01',
    progress_cache: { story_count: 3, done_count: 1 },
    correlation_id: null,
    archived_at: null,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-04T12:00:00.000Z',
  },
  {
    id: 'epic-002',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Agent Collaboration Plane',
    slug: 'agent-collaboration-plane',
    description_json: null,
    description_md:
      'First-class AI agents as workspace members with governed write paths and activity streams.',
    status_id: EPIC_STATUS_IDS.planned,
    priority: 'medium',
    lead_id: null,
    delegate_agent_id: 'agent-landi-flow-builtin',
    start_date: null,
    target_date: null,
    progress_cache: null,
    correlation_id: null,
    archived_at: null,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-02T14:00:00.000Z',
  },
  {
    id: 'epic-003',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'OBS-001 Observability Spine',
    slug: 'obs-001-observability-spine',
    description_json: null,
    description_md:
      'End-to-end correlation IDs from client error boundaries through Workers to AI Gateway.',
    status_id: EPIC_STATUS_IDS.backlog,
    priority: 'urgent',
    lead_id: null,
    delegate_agent_id: null,
    start_date: null,
    target_date: null,
    progress_cache: null,
    correlation_id: null,
    archived_at: null,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-01T10:00:00.000Z',
  },
  {
    id: 'epic-004',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Epic Board Polish',
    slug: 'epic-board-polish',
    description_json: null,
    description_md: 'Kanban-style Epic roadmap with burn-up progress and dependency hints.',
    status_id: EPIC_STATUS_IDS.completed,
    priority: 'none',
    lead_id: 'user-alex',
    delegate_agent_id: null,
    start_date: '2026-06-15',
    target_date: '2026-06-28',
    progress_cache: { story_count: 1, done_count: 1 },
    correlation_id: null,
    archived_at: null,
    created_at: '2026-06-15T10:00:00.000Z',
    updated_at: '2026-06-28T16:00:00.000Z',
  },
];

export const DEMO_CYCLES: Cycle[] = [
  {
    id: 'cycle-23',
    team_id: DEMO_TEAM_ID,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Cycle 23',
    number: 23,
    starts_at: '2026-06-16T00:00:00.000Z',
    ends_at: '2026-06-30T00:00:00.000Z',
    completed_at: '2026-06-30T00:00:00.000Z',
    settings: {},
    created_at: '2026-06-01T10:00:00.000Z',
    updated_at: '2026-06-30T00:00:00.000Z',
  },
  {
    id: 'cycle-24',
    team_id: DEMO_TEAM_ID,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Cycle 24',
    number: 24,
    starts_at: '2026-07-01T00:00:00.000Z',
    ends_at: '2026-07-14T00:00:00.000Z',
    completed_at: null,
    settings: {},
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-01T10:00:00.000Z',
  },
];

export const SEED_STORIES: Story[] = [
  {
    id: 'story-001',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 1,
    epic_id: 'epic-001',
    identifier: 'LAN-1',
    title: 'Implement three-panel SidebarLayout shell',
    description_json: null,
    description_md:
      'Wire SidebarLayout from @landi-flow/ui with collapsible sidebar and inspector.',
    priority: 'high',
    workflow_state_id: WORKFLOW_STATES.done,
    assignee_id: 'user-jane',
    creator_id: 'user-jane',
    follower_ids: ['user-alex'],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: 'cycle-24',
    estimate: 3,
    due_date: null,
    sort_order: 1,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-02T09:00:00.000Z',
    updated_at: '2026-07-04T11:00:00.000Z',
  },
  {
    id: 'story-002',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 2,
    epic_id: 'epic-001',
    identifier: 'LAN-2',
    title: 'Command palette with suggested actions',
    description_json: null,
    description_md: 'Cmd+K palette shows contextual suggested actions when query is empty.',
    priority: 'medium',
    workflow_state_id: WORKFLOW_STATES.in_progress,
    assignee_id: 'user-jane',
    creator_id: 'user-jane',
    follower_ids: ['user-jane', 'user-alex'],
    delegate_agent_id: 'agent-cursor-external',
    milestone_id: null,
    cycle_id: 'cycle-24',
    estimate: 2,
    due_date: null,
    sort_order: 2,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-02T10:00:00.000Z',
    updated_at: '2026-07-04T12:30:00.000Z',
  },
  {
    id: 'story-003',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 3,
    epic_id: 'epic-001',
    identifier: 'LAN-3',
    title: 'G-key navigation tooltips',
    description_json: null,
    description_md:
      'Press G and pause 500ms to reveal secondary keystroke hints on nav targets.',
    priority: 'low',
    workflow_state_id: WORKFLOW_STATES.todo,
    assignee_id: null,
    creator_id: 'user-alex',
    follower_ids: [],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: 'cycle-24',
    estimate: 1,
    due_date: null,
    sort_order: 3,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-03T08:00:00.000Z',
    updated_at: '2026-07-03T08:00:00.000Z',
  },
  {
    id: 'story-004',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 4,
    epic_id: 'epic-002',
    identifier: 'LAN-4',
    title: 'Agent avatar active-state glow',
    description_json: null,
    description_md: 'Animated border on agent avatars when background processing is active.',
    priority: 'medium',
    workflow_state_id: WORKFLOW_STATES.todo,
    assignee_id: null,
    creator_id: 'user-jane',
    follower_ids: ['user-alex'],
    delegate_agent_id: 'agent-cursor-external',
    milestone_id: null,
    cycle_id: 'cycle-24',
    estimate: 2,
    due_date: null,
    sort_order: 4,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-03T11:00:00.000Z',
    updated_at: '2026-07-03T11:00:00.000Z',
  },
  {
    id: 'story-005',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 5,
    epic_id: 'epic-003',
    identifier: 'LAN-5',
    title: 'Error boundary with correlation ID',
    description_json: null,
    description_md: 'Inline ErrorFallback cards include copyable trace IDs per OBS-001.',
    priority: 'urgent',
    workflow_state_id: WORKFLOW_STATES.in_progress,
    assignee_id: 'user-alex',
    creator_id: 'user-alex',
    follower_ids: ['user-jane'],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: 2,
    due_date: null,
    sort_order: 5,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    sla_id: 'sla-demo',
    sla_due_at: '2026-07-01T12:00:00.000Z',
    created_at: '2026-07-04T08:00:00.000Z',
    updated_at: '2026-07-04T13:00:00.000Z',
  },
  {
    id: 'story-006',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 6,
    epic_id: 'epic-004',
    identifier: 'LAN-6',
    title: 'Epic board column layout',
    description_json: null,
    description_md: 'Status columns with Epic cards, progress chips, and empty-state CTA.',
    priority: 'none',
    workflow_state_id: WORKFLOW_STATES.done,
    assignee_id: 'user-alex',
    creator_id: 'user-alex',
    follower_ids: [],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: 'cycle-23',
    estimate: 3,
    due_date: null,
    sort_order: 6,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-06-20T09:00:00.000Z',
    updated_at: '2026-06-28T15:00:00.000Z',
  },
  {
    id: 'story-007',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 7,
    epic_id: 'epic-002',
    identifier: 'LAN-7',
    title: 'Document agent runtime metadata',
    description_json: null,
    description_md:
      'Post-hoc attribution: work completed offline but credited to an attribution-only agent identity.',
    priority: 'medium',
    workflow_state_id: WORKFLOW_STATES.done,
    assignee_id: 'user-jane',
    creator_id: 'user-jane',
    follower_ids: [],
    delegate_agent_id: 'agent-attribution-demo',
    milestone_id: null,
    cycle_id: null,
    estimate: 2,
    due_date: null,
    sort_order: 7,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-05T09:00:00.000Z',
    updated_at: '2026-07-06T10:00:00.000Z',
  },
  {
    id: 'story-draft-001',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 8,
    epic_id: 'epic-001',
    identifier: 'LAN-8',
    title: 'Draft: keyboard shortcut reference overlay',
    description_json: null,
    description_md: 'WIP spec for G-key and Cmd+K discoverability — publish when ready.',
    priority: 'none',
    workflow_state_id: WORKFLOW_STATES.todo,
    assignee_id: null,
    creator_id: 'user-jane',
    follower_ids: [],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: null,
    due_date: null,
    sort_order: 8,
    is_draft: true,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-06T09:00:00.000Z',
    updated_at: '2026-07-06T09:00:00.000Z',
  },
  {
    id: 'story-triage-001',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 9,
    epic_id: null,
    identifier: 'LAN-9',
    title: 'Inbound: Slack #asks feature request',
    description_json: null,
    description_md: 'Customer asked for bulk milestone assignment via Shift+M.',
    priority: 'medium',
    workflow_state_id: WORKFLOW_STATES.triage,
    assignee_id: null,
    creator_id: 'user-alex',
    follower_ids: [],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: null,
    due_date: null,
    sort_order: 9,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
  },
  {
    id: 'story-triage-002',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    number: 10,
    epic_id: 'epic-001',
    identifier: 'LAN-10',
    title: 'Inbound: email support escalation',
    description_json: null,
    description_md: 'Needs triage — assign to epic after acceptance.',
    priority: 'high',
    workflow_state_id: WORKFLOW_STATES.triage,
    assignee_id: null,
    creator_id: 'user-jane',
    follower_ids: [],
    delegate_agent_id: null,
    milestone_id: null,
    cycle_id: null,
    estimate: null,
    due_date: null,
    sort_order: 10,
    is_draft: false,
    archived_at: null,
    correlation_id: null,
    created_at: '2026-07-07T08:30:00.000Z',
    updated_at: '2026-07-07T08:30:00.000Z',
  },
];

/** CAP-050: demo milestones for epic-001. */
export const SEED_MILESTONES: Milestone[] = [
  {
    id: 'milestone-alpha',
    epic_id: 'epic-001',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Alpha — shell + navigation',
    description: 'Core shell, sidebar, and keyboard nav complete.',
    target_date: '2026-07-15',
    position: 0,
    completed_at: null,
    issue_count: 2,
    completed_issue_count: 1,
    progress_pct: 50,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-04T12:00:00.000Z',
  },
  {
    id: 'milestone-beta',
    epic_id: 'epic-001',
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Beta — views engine',
    description: 'Saved views, column prefs, and board quick-add.',
    target_date: '2026-07-28',
    position: 1,
    completed_at: null,
    issue_count: 1,
    completed_issue_count: 0,
    progress_pct: 0,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-04T12:00:00.000Z',
  },
];

/** CAP-029/030: demo saved views. */
export const SEED_SAVED_VIEWS: View[] = [
  {
    id: 'view-my-active',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    epic_id: null,
    owner_id: 'user-jane',
    name: 'My active Stories',
    description: 'Assigned to me, not done',
    scope: 'personal',
    layout: 'list',
    filter_ast: { op: 'and', conditions: [{ field: 'assignee', operator: 'is', values: ['user-jane'] }] },
    display_options: { layout: 'list' },
    grouping: 'status',
    sub_grouping: null,
    is_shared: false,
    is_favorited: true,
    created_at: '2026-07-01T10:00:00.000Z',
    updated_at: '2026-07-04T12:00:00.000Z',
  },
  {
    id: 'view-team-board',
    workspace_id: DEMO_WORKSPACE_ID,
    team_id: DEMO_TEAM_ID,
    epic_id: null,
    owner_id: 'user-alex',
    name: 'Team board — shared',
    description: 'Shared Kanban for Team Design',
    scope: 'team',
    layout: 'board',
    filter_ast: {},
    display_options: { layout: 'board' },
    grouping: null,
    sub_grouping: null,
    is_shared: true,
    is_favorited: false,
    created_at: '2026-07-02T10:00:00.000Z',
    updated_at: '2026-07-04T12:00:00.000Z',
  },
];

export function getEpicById(epicId: string): Epic | undefined {
  return SEED_EPICS.find((epic) => epic.id === epicId);
}

export function getStoriesForEpic(epicId: string): Story[] {
  return SEED_STORIES.filter((story) => story.epic_id === epicId);
}

export function getStoryById(storyId: string): Story | undefined {
  return SEED_STORIES.find((story) => story.id === storyId);
}

/** Demo customer record for the Customers index (CAP-066). */
export interface CustomerRecord {
  id: string;
  name: string;
  domain: string;
  tier?: string | null;
  revenue?: number | null;
  status?: string;
}

/** Seed customers — demo row for filter dimension CAP-068. */
export const SEED_CUSTOMERS: CustomerRecord[] = [
  {
    id: 'customer-acme',
    name: 'Acme Corp',
    domain: 'acme.example',
    tier: 'enterprise',
    revenue: 120000,
    status: 'active',
  },
];

/** CAP-067/073 seed customer requests for mock mode. */
export const SEED_CUSTOMER_REQUESTS: CustomerRequest[] = [
  {
    id: 'request-001',
    workspace_id: DEMO_WORKSPACE_ID,
    customer_id: 'customer-acme',
    quote: 'Need SSO for enterprise rollout',
    source: 'slack',
    source_url: 'https://slack.com/archives/asks',
    requester_name: 'Taylor',
    is_important: true,
    correlation_id: 'corr-request-001',
    story_ids: [],
    epic_ids: [],
    created_at: '2026-07-05T10:00:00.000Z',
    updated_at: '2026-07-05T10:00:00.000Z',
  },
];
